// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NellieBot.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NellieBot.Migrations
{
  [DbContext(typeof(DatabaseContext))]
  [Migration("20230907160044_Initial")]
  partial class Initial
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("ProductVersion", "7.0.10")
        .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("NellieBot.Database.Entities.WarnData", b =>
          {
            b.Property<int>("Id")
              .HasColumnType("integer");

            b.Property<decimal>("UserId")
              .HasColumnType("numeric(20,0)");

            b.Property<DateTime>("DateTime")
              .HasColumnType("timestamp with time zone");

            b.Property<string>("Note")
              .IsRequired()
              .HasColumnType("text");

            b.Property<string>("Reason")
              .IsRequired()
              .HasColumnType("text");

            b.HasKey("Id", "UserId");

            b.ToTable("WarnData");
          });
#pragma warning restore 612, 618
    }
  }
}
